In [1]:
import numpy as np

In [2]:
a = np.arange(25, dtype='float').reshape(5,5)

In [4]:
a.ndim

2

In [5]:
a.size

25

In [7]:
a.dtype

dtype('float64')

In [8]:
a.itemsize

8

In [9]:
type(a)

numpy.ndarray

In [15]:
b = np.array([1.,2.3,4,5.1], dtype='complex')

In [16]:
b.dtype

dtype('complex128')

In [23]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.empty((2,3))

array([[4.66676778e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [28]:
np.arange(3,126,20)

array([  3,  23,  43,  63,  83, 103, 123])

In [31]:
from numpy import pi

In [37]:
#linspace son paramaetre kaç eleman oldugu
#arange de son parametere basamak sayısı alır
x = np.linspace(0, 2*pi, 100)
y = np.arange(0,100,3)

In [48]:
a = np.array([10,20,30,5])
b = np.arange(4)

In [49]:
a-b

array([10, 19, 28,  2])

In [50]:
a*np.sin(b)

array([ 0.        , 16.8294197 , 27.2789228 ,  0.70560004])

In [51]:
a<20

array([ True, False, False,  True])

In [52]:
# '@' --> matrix prdouct || '.dot' --> matrix product

In [57]:
rg = np.random.default_rng(1)
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [58]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [59]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [62]:
# cumsum --> cumulative sum along each row
b = np.arange(12).reshape(3,4)
b.sum(axis=0)   # colum sum for this array
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [63]:
np.exp(b)  # ufunc --> universal function

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [66]:
# fromfunction using with tuple() paramters
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(4,5),dtype=complex)
b

array([[ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
       [10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j, 14.+0.j],
       [20.+0.j, 21.+0.j, 22.+0.j, 23.+0.j, 24.+0.j],
       [30.+0.j, 31.+0.j, 32.+0.j, 33.+0.j, 34.+0.j]])

In [67]:
c = np.arange(12).reshape(2,2,3)

In [72]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [76]:
#c.ravel()   # returned flattened array
c.T   # c'S tranpose vectorizian

array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])

In [77]:
c.reshape(3,-1)  # '-1', automatically calculated

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
a = c.view()
c is a

False

In [84]:
b = c.copy()

In [85]:
# arg istenen degerin bulundugu indexi veriyor.
data = np.sin(np.arange(20)).reshape(5,4)
ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1])