In [1]:
a = [1,2,3,4,5]
b = [10,11,23,14,15]

In [2]:
a+b

[1, 2, 3, 4, 5, 10, 11, 23, 14, 15]

In [3]:
result = []
for first, second in zip(a,b):
    result.append(first+second)

In [4]:
result

[11, 13, 26, 18, 20]

In [5]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])

In [8]:
type(a)

numpy.ndarray

In [9]:
 a.dtype

dtype('int64')

In [10]:
f = np.array([1.2,2.3,3.4,4.5,5.6])

In [11]:
f.dtype

dtype('float64')

In [12]:
a[0]

1

In [13]:
a[0] = 10

In [14]:
a

array([10,  2,  3,  4])

In [15]:
a[0] = 11.5

In [16]:
a

array([11,  2,  3,  4])

In [17]:
a.ndim

1

In [18]:
a.shape

(4,)

In [19]:
a.size

4

In [24]:
a = np.array([1,2,3,4,5])

In [25]:
f

array([1.2, 2.3, 3.4, 4.5, 5.6])

In [26]:
a + f

array([ 2.2,  4.3,  6.4,  8.5, 10.6])

In [27]:
a * f

array([ 1.2,  4.6, 10.2, 18. , 28. ])

In [28]:
a / f

array([0.83333333, 0.86956522, 0.88235294, 0.88888889, 0.89285714])

In [29]:
f ** a

array([1.20000000e+00, 5.29000000e+00, 3.93040000e+01, 4.10062500e+02,
       5.50731776e+03])

In [30]:
a

array([1, 2, 3, 4, 5])

In [31]:
a * 10

array([10, 20, 30, 40, 50])

In [32]:
# universal functions
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [33]:
np.sum(a)

15

In [34]:
#!!!!!!!!!!!!!!
c = np.array([[1,2,3],[3,4,5]])

In [35]:
c[1]

array([3, 4, 5])

In [37]:
c[1,2]

5

In [38]:
a[1:3]

array([2, 3])

In [39]:
a[::2]

array([1, 3, 5])

In [40]:
a[-2:]

array([4, 5])