In [1]:
import numpy as np

In [2]:
np.nan

nan

In [3]:
a = np.ones((3,5))
b = np.ones((5,))
b.reshape(1,5)
b[np.newaxis, :]

array([[1., 1., 1., 1., 1.]])

In [4]:
a+b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [7]:
import random
a = np.arange(25).reshape(5,5)

In [8]:
a.sum()

300

In [9]:
a.sum(axis=0)

array([50, 55, 60, 65, 70])

In [11]:
a.sum(axis=-1)

array([ 10,  35,  60,  85, 110])

In [12]:
a = np.ones((5,6))

In [13]:
a.shape

(5, 6)

In [15]:
a.sum(axis=0).shape

(6,)

In [16]:
a.sum(axis=0)

array([5., 5., 5., 5., 5., 5.])

In [17]:
# sum, prod, min,max, argmin, ptp(min-max), mean, std, var

In [18]:
#any, all
np.std(a)

0.0

In [19]:
np.any(a)

True

In [21]:
a = np.array([-1,2,5,5])

In [22]:
a == a.max()

array([False, False,  True,  True])

In [23]:
np.where(a == a.max())

(array([2, 3]),)

In [24]:
np.where(a > 3)

(array([2, 3]),)

In [6]:
# example...
import numpy as np
time = np.linspace(20,145,5)
data = np.sin(np.arange(20)).reshape(5,4)
print('time: ', time, 'len: ', len(time))
#print('data: ', data)

ind = data.argmax(axis=0)
print('indices: ', ind)

time_max  = time[ind]
data_max = data[ind, range(data.shape[1])]
np.all(data_max == data.max(axis=0))

time:  [ 20.    51.25  82.5  113.75 145.  ] len:  5
indices:  [2 0 3 1]


True

In [7]:
a = np.arange(5)
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [8]:
a[[0,0,2]] += 1
a

array([1, 0, 3, 0, 0])

In [9]:
# masking in array
a = np.arange(12).reshape(3,4)
b = a > 4
print('b : ', b)
a[b]

b :  [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


array([ 5,  6,  7,  8,  9, 10, 11])