In [1]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5,6])
print(a.shape)
a2 = a[np.newaxis, :]
print(a2.shape)

col_vector = a[:, np.newaxis]
print(col_vector.shape)

b = np.expand_dims(a, axis=1)
print(b.shape)
c = np.expand_dims(a, axis=0)
print(c.shape)

(6,)
(1, 6)
(6, 1)
(6, 1)
(1, 6)


In [14]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

five_up = (a >= 5)
print(a[five_up])

div_by_2 = a[a%2==0]
print(div_by_2)

cond = (a > 2) & (a < 11)
c = a[cond]
print(cond)

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[[False False  True  True]
 [ True  True  True  True]
 [ True  True False False]]


In [18]:
b = np.nonzero(a < 5)
print(b)

list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)
    
print(a[b])

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
(0, 0)
(0, 1)
(0, 2)
(0, 3)
[1 2 3 4]


In [23]:
#create array from existing array

a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [29]:
x = np.arange(1,25).reshape(2,12)
print(x)

print(np.hsplit(x,3))

print(np.hsplit(x, (3,4)))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [37]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([1,1])  # uzatılır (2,)-->(3,2)'e..
print(data + ones_row)

rng = np.random.default_rng(0)
print(np.random.random((2,3,2)))

[[2 3]
 [4 5]
 [6 7]]
[[[0.16125535 0.49883163]
  [0.39311696 0.30271337]
  [0.63099689 0.50478433]]

 [[0.24008515 0.72225394]
  [0.11217434 0.04223132]
  [0.67269151 0.69760194]]]


In [43]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)
print(unique_values)

unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
unique_rows = np.unique(a_2d, axis=0)
unique_rows, indices, occurrence_count = np.unique(
        a_2d, axis=0, return_counts=True, return_index=True)
print("unique rows: ", unique_rows)
print("indices: ", indices)
print("occure..: ", occurrence_count)

[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]
[3 2 2 2 1 1 1 1 1 1]
unique rows:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
indices:  [0 1 2]
occure..:  [2 1 1]


In [47]:
# help(np.unique)
# np.unique?
# len??
"""
    np.savetxt('filename', array)
    np.loadtxt('filename')
    file --> might be a .csv or .npy
"""