In [2]:
import numpy as np

In [3]:
a = np.arange(36).reshape(6,6)
for i in range(6):
    a[i] = a[i] + 4*i

In [4]:
a.shape

(6, 6)

In [5]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [6]:
a[0, 3:5]

array([3, 4])

In [7]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [8]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [9]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [10]:
a = np.arange(25).reshape(5,5)

In [11]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
a[:, 1::2]  # initial column: 1 !!!!

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [13]:
a[1::2, :3:2]

array([[ 5,  7],
       [15, 17]])

In [14]:
a[-1]

array([20, 21, 22, 23, 24])

In [15]:
a = np.arange(4)

In [16]:
b = a[:2]

In [17]:
b

array([0, 1])

In [18]:
b.__getitem__(0)

0

In [19]:
b.__setitem__(0, 100)

In [20]:
b

array([100,   1])

In [21]:
np.array.__call__([1,2,3])

array([1, 2, 3])

In [22]:
a = np.arange(0,80,10)

In [23]:
indices = [1,2,-3]
y = a[indices]
y

array([10, 20, 50])

In [24]:
a = np.array([-1,-3,1,4,-6,9,3])

In [25]:
a < 0

array([ True,  True, False, False,  True, False, False])

In [26]:
#masking
negative = a < 0

In [27]:
a[negative]

array([-1, -3, -6])

In [28]:
a[negative] = 0

In [29]:
a

array([0, 0, 1, 4, 0, 9, 3])

In [30]:
a = np.arange(36).reshape(6,6)
for i in range(6):
    a[i] = a[i] + 4*i

In [31]:
a[[0,1,2,3,4],[1,2,3,4,5]]

array([ 1, 12, 23, 34, 45])

In [32]:
a[3: , [0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [33]:
# masking rowwss!!!!!!!
mask = np.array([1,0,1,0,0,1],dtype=bool)
a[mask,2]

array([ 2, 22, 52])

In [34]:
b = np.arange(25).reshape(5,5)

In [36]:
b[[0,2,3,3],[2,3,1,-1]]

array([ 2, 13, 16, 19])

In [37]:
mask = np.array([0,1,1,1,1], dtype=bool)

In [39]:
a % 3 == 0

array([[ True, False, False,  True, False, False],
       [False, False,  True, False, False,  True],
       [False,  True, False, False,  True, False],
       [ True, False, False,  True, False, False],
       [False, False,  True, False, False,  True],
       [False,  True, False, False,  True, False]])

In [40]:
a[a%3==0]

array([ 0,  3, 12, 15, 21, 24, 30, 33, 42, 45, 51, 54])