In [26]:
from numpy import loadtxt
import numpy as np

In [27]:
data = loadtxt('wind.data')

In [28]:
data

array([[61.  ,  1.  ,  1.  , ..., 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , ...,  9.67, 17.54, 13.83],
       [61.  ,  1.  ,  3.  , ...,  7.67, 12.75, 12.71],
       ...,
       [78.  , 12.  , 29.  , ..., 16.42, 18.88, 29.58],
       [78.  , 12.  , 30.  , ..., 12.12, 14.67, 28.79],
       [78.  , 12.  , 31.  , ..., 11.38, 12.08, 22.08]])

In [29]:
data.shape

(6574, 15)

In [30]:
data[:4]

array([[61.  ,  1.  ,  1.  , 15.04, 14.96, 13.17,  9.29, 13.96,  9.87,
        13.67, 10.25, 10.83, 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , 14.71, 16.88, 10.83,  6.5 , 12.62,  7.67,
        11.5 , 10.04,  9.79,  9.67, 17.54, 13.83],
       [61.  ,  1.  ,  3.  , 18.5 , 16.88, 12.33, 10.13, 11.17,  6.17,
        11.25,  8.04,  8.5 ,  7.67, 12.75, 12.71],
       [61.  ,  1.  ,  4.  , 10.58,  6.63, 11.75,  4.58,  4.54,  2.88,
         8.63,  1.79,  5.83,  5.88,  5.46, 10.88]])

In [31]:
dates = data[:, :3]
winds = data[:,3:]


In [32]:
print('min:',winds.min(), 'max',
winds.max(), 'mean:',
winds.mean(), 'std:',
winds.std())

min: 0.0 max 42.54 mean: 10.22837377040868 std: 5.603840181095793


In [33]:
winds.min(axis=0).shape # aspect to column

(12,)

In [34]:
winds.min(axis=0)

array([0.67, 0.21, 1.5 , 0.  , 0.13, 0.  , 0.  , 0.  , 0.  , 0.04, 0.13,
       0.67])

In [35]:
winds.std(axis=0)

array([5.61918301, 5.26820081, 5.00738377, 3.60513309, 4.93536333,
       3.96838126, 4.97689374, 4.49865783, 4.16746101, 4.50327222,
       5.83459319, 6.69734719])

In [36]:
winds.argmax(axis=1)

array([10, 10,  0, ..., 11, 11,  2])

In [37]:
np.where(winds == winds.max())

(array([2161]), array([11]))

In [38]:
winds.argmax()

25943

In [39]:
winds.max(axis=1) #calculte about rows

array([18.5 , 17.54, 18.5 , ..., 29.58, 28.79, 27.29])

In [46]:
januaries = dates[:,1] == 1
januaries

array([ True,  True,  True, ..., False, False, False])

In [43]:
januaries.shape

(6574,)

In [45]:
winds[januaries].mean(axis=0)

array([14.86955197, 12.92166667, 13.29962366,  7.19949821, 11.67571685,
        8.05483871, 11.81935484,  9.5094086 ,  9.54320789, 10.05356631,
       14.55051971, 18.02876344])